DROP TABLE nichhlnr_main.BLOGS;
CREATE TABLE nichhlnr_main.BLOGS(
  BLOG_ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  BLOG_TITLE VARCHAR (100) NOT NULL,
  BLOG_DESCRIPTION VARCHAR (500) NOT NULL,
  BLOG_INFORMATION VARCHAR (50000) NOT NULL,
  BLOG_PERMA_LINK VARCHAR (50) NOT NULL,
  CREATE_DTTM TIMESTAMP DEFAULT 0,
  UPDATE_DTTM TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  ACTIVE_FLG VARCHAR (1) DEFAULT 'Y'
);

DROP TABLE nichhlnr_main.BLOG_POSTS;
CREATE TABLE nichhlnr_main.BLOG_POSTS(
  BLOG_POST_ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  BLOG_ID INT NOT NULL,
  BLOG_POST_TITLE VARCHAR(100) NOT NULL,
  BLOG_POST_DESCRIPTION VARCHAR(500) NOT NULL,
  BLOG_POST_CONTENT VARCHAR(50000) NOT NULL,
  BLOG_POST_PERMA_LINK VARCHAR(50) NOT NULL,
  CREATE_DTTM TIMESTAMP DEFAULT 0,
  UPDATE_DTTM TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  ACTIVE_FLG VARCHAR(1) DEFAULT 'Y'
);

SELECT * FROM BLOGS;
SELECT * FROM BLOG_POSTS;

INSERT INTO nichhlnr_main.BLOGS (BLOG_TITLE, BLOG_DESCRIPTION, BLOG_PERMA_LINK, BLOG_INFORMATION, CREATE_DTTM) VALUES ('My First Blog', 'Just a quick test', 'my-first-blog', 'This is just a test to see how my blog will be displayed when opened. This text is what I stored in the BLOG_INFORMATION column in the database and I hope to put it on the right panel when this blog is opened. Hopefully it''s possible without a ton of fixes...', NULL);
INSERT INTO nichhlnr_main.BLOG_POSTS(BLOG_ID, BLOG_POST_TITLE, BLOG_POST_DESCRIPTION, BLOG_POST_CONTENT, BLOG_POST_PERMA_LINK, CREATE_DTTM) VALUES (1, 'My First Post', 'This is a quick description of my first post', 'What is special about this post is that its my first, which I will now explain in this content', 'my-first-post', NULL);
COMMIT;