GRANT ALL ON NICHOLAS_AZAR.* TO 'NICHOLAS_AZAR';

DROP TABLE NICHOLAS_AZAR.BLOGS;
CREATE TABLE NICHOLAS_AZAR.BLOGS (
  BLOG_ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  BLOG_TITLE VARCHAR(100),
  BLOG_DESCRIPTION VARCHAR(500),
  BLOG_PERMA_LINK VARCHAR(50),
  CREATE_DTTM DATETIME DEFAULT NOW(),
  UPDATE_DTTM DATETIME ON UPDATE NOW(),
  ACTIVE_FLG VARCHAR(1) DEFAULT 'Y'
);

DROP TABLE NICHOLAS_AZAR.BLOG_POSTS;
CREATE TABLE NICHOLAS_AZAR.BLOG_POSTS(
  BLOG_POST_ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  BLOG_ID INT,
  BLOG_POST_TITLE VARCHAR(100),
  BLOG_POST_DESCRIPTION VARCHAR(500),
  BLOG_POST_CONTENT VARCHAR(50000),
  CREATE_DTTM DATETIME DEFAULT NOW(),
  UPDATE_DTTM DATETIME ON UPDATE NOW(),
  ACTIVE_FLG VARCHAR(1) DEFAULT 'Y'
);

SELECT * FROM BLOGS;

ALTER TABLE NICHOLAS_AZAR.BLOGS MODIFY ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY;

INSERT INTO NICHOLAS_AZAR.BLOGS (TITLE, DESCRIPTION, PERMA_LINK) VALUES ('My First Blog', 'Just a quick test', 'my-first-blog');